# Generated by Django 3.0.4 on 2020-03-13 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('publishedAt', models.DateField()),
                ('thumbnail', models.URLField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=3)),
                ('viewCount', models.PositiveIntegerField()),
                ('videoCount', models.PositiveIntegerField()),
                ('subscriberCount', models.PositiveIntegerField()),
                ('playlist_id', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=128)),
                ('photo', models.FileField(upload_to='')),
                ('description', models.TextField()),
                ('birthday', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.Channel')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='Video_Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishedAt', models.DateField()),
                ('viewAt', models.DateField()),
                ('viewCount', models.PositiveIntegerField()),
                ('likeCount', models.PositiveIntegerField()),
                ('dislikeCount', models.PositiveIntegerField()),
                ('commentCount', models.PositiveIntegerField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.Video')),
            ],
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
